FROM nginx:1.25-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/certs/server.crt /etc/nginx/certs/server.crt
COPY docker/nginx/certs/server.key /etc/nginx/certs/server.key
